/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{js,jsx,ts,tsx}", "./src/**/*.{js,jsx,ts,tsx}"],
  darkMode: "class",
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        // Original Garaji Colors
        ink: "#2F1500",
        muted: "#6E5746",
        line: "#E7D2BF",
        surface: "#FFF7EF",
        "surface-soft": "#FFE8D4",
        card: "#FFFFFF",
        brand: {
          50: "#FFF0DF",
          100: "#FFDCC3",
          500: "#FFB77D",
          600: "#FF8C00",
          700: "#904D00",
        },
        action: {
          50: "#EAF4FF",
          100: "#D8E2FF",
          500: "#85CFFF",
          600: "#4B8EFF",
          700: "#004493",
        },
        gold: {
          50: "#FFF7E8",
          100: "#FFE8BA",
          505: "#F59E0B",
          500: "#F59E0B",
          600: "#D97706",
          700: "#B45309",
        },

        // Stitch Material 3 Tokens (DESIGN.md)
        primary: "#0D9488",
        "on-primary": "#FFFFFF",
        "primary-container": "#ccfbf1",
        "on-primary-container": "#115e59",
        "surface-container-lowest": "#FFFFFF",
        "surface-container-low": "#F9FAFB",
        "surface-container": "#F3F4F6",
        "surface-container-high": "#E5E7EB",
        "surface-container-highest": "#D1D5DB",
        "on-surface": "#1A1A2E",
        "on-surface-variant": "#6B7280",
        outline: "#E5E7EB",
        "outline-variant": "#D1D5DB",
        error: "#EF4444",
        "error-container": "#FEE2E2",
        secondary: "#6B7280",
        "secondary-container": "#F3F4F6",

        "dark-surface": "#1B110A",
        "dark-card": "#281D15",
        "dark-ink": "#F3DFD1",
        "dark-muted": "#DDC1AE",
        "dark-line": "#564334",
      },
      spacing: {
        'margin-mobile': '16px',
        'margin-desktop': '32px',
        'gutter': '16px',
        'stack-sm': '8px',
        'stack-md': '16px',
        'stack-lg': '24px',
      },
      fontSize: {
        'display-lg': ['32px', { lineHeight: '40px' }],
        'display-lg-mobile': ['28px', { lineHeight: '36px' }],
        'title-md': ['20px', { lineHeight: '28px' }],
        'body-md': ['16px', { lineHeight: '24px' }],
        'label-sm': ['13px', { lineHeight: '18px' }],
        'button-text': ['16px', { lineHeight: '24px' }],
      },
      fontFamily: {
        sans: ["Tajawal", "System"],
        tajawal: ["Tajawal"],
        "tajawal-medium": ["Tajawal_500Medium"],
        "tajawal-bold": ["Tajawal_700Bold"],
        "display-lg": ["Tajawal_700Bold"],
        "display-lg-mobile": ["Tajawal_700Bold"],
        "title-md": ["Tajawal_700Bold"],
        "body-md": ["Tajawal"],
        "label-sm": ["Tajawal_500Medium"],
        "button-text": ["Tajawal_700Bold"],
      },
      boxShadow: {
        "tactile-sm": "0 1px 2px rgba(15, 23, 42, 0.06), 0 1px 8px rgba(2, 132, 199, 0.05)",
        "tactile-md":
          "0 14px 34px rgba(15, 23, 42, 0.10), 0 3px 10px rgba(2, 132, 199, 0.08)",
      },
    },
  },
  plugins: [],
};
